name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    steps:
      # Checks-out your repository u job can access it

      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 18.13.0
        uses: actions/setup-node@v1
        with:
          node-version: '18.13.0'
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build --prod
        

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: roshanadi
          password: dckr_pat_YU9W4wnO1iTAFDTyU2hRe5GWLr0
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: roshanadi/chatapp:lates
